name: Review workflow to be applied 
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

jobs:
  sayHi:
   runs-on: ubuntu-latest
   steps:
   - run: echo 'Hello'
  
